### ISSUE TITLE
Question about the HW of last lecture

### ISSUE THREAD

**Issue by shizejin** [oyamad/theory16#3]
Dear professor Oyama,

I suppose we have to finish the homework about using Lemke-Howson algorithm to prove kakutani theorem before next Tue. I wonder whether we should find a specific correspondence F by ourselves or you will set it for us?

Best, Zejin

**Comment by oyamad** [comment]
Any function is fine (consider functions rather than correspondences).
The simplest is f(x) = q x with one dimensional variable (Example 4.2).

You may also consider Example 4.6, where you should start with a smaller dimension.

**Comment by shizejin** [comment]
I think Kakutani theory is about correspondence, are we confining to functions for simplicity of programming? 

And where can I find Example 4.2 and 4.6? I am sorry, but I didn't see this in the slides.

**Comment by oyamad** [comment]
McLennan and Tourky in the reading list.

Of course you can consider correspondences if you want. Functions are easier.

**Comment by shizejin** [comment]
Got it, thank you very much!
