### ISSUE TITLE
Dynamic Programming: Comparison of three methods

### ISSUE THREAD

**Issue by shizejin** [oyamad/theory16#4]
Presentation in 1/11 will be about comparing three methods for numerically solving dynamic programming problems, which are Value Function Iteration, Policy Function Iteration, and Endogenous Grid Points.  
I will follow the lecture notes by [ZICE 2014](https://github.com/davidrpugh/zice-2014/blob/master/endogenous-gridpoint-methods/iskhakov_egm_zice2014.pdf). The specific problem  to be solved is from [A Simple Optimal Growth Model](http://lectures.quantecon.org/py/optgrowth.html#id15) in [Quantitive Economics](http://lectures.quantecon.org). I use the same code in Value Function Iteration, and then extend it to Policy Iteration and Endogenous Grid Points.

**Comment by oyamad** [comment]
Good.
Will you also include your own code from the previous homework (i.e., the code that computes a fixed point by imitation games)?

**Comment by shizejin** [comment]
Sure, if there is time left, I would like to include those previous homework (which are computing a fixed point by imitation games and Experimental Analysis of Lemke Howson Algorithm).

**Comment by shizejin** [comment]
Here is my [code](http://nbviewer.jupyter.org/github/shizejin/theory16HW/blob/master/Dynamic%20Programming.ipynb).

**Comment by oyamad** [comment]
So why don't you use your fixed point computation routine in place of `qe.compute_fixed_point`.

**Comment by shizejin** [comment]
Do you mean use qe.compute_fixed_point to replace fmin function in Dynamic Programming?

**Comment by oyamad** [comment]
No.
The optimal value function is a fixed point of the Bellman operator. Any fixed point solver can in theory find an (approximate) optimal value function. So why not use your own.
For example, you can just replace `qe.compute_fixed_point` in cell `[6]` with your routine.

**Comment by shizejin** [comment]
I see your point.  Later I defined a function named 'iteration' to compute the fixed points for operators that are contraction mapping. Cell [6] is a part copied from Quant Econ to introduce the background of the problem.
