### ISSUE TITLE
pure nash brute force method

### ISSUE THREAD

**Issue by shizejin** [oyamad/theory16#7]
Dear professor Oyama,

I've pushed pure nash brute force method to my fork "QuantEcon.py" repository. It would be great if you could help me check it at your convenience. 

I just slightly added something to the codes in your "Tools for Game Theory" notebook, and write the descriptions and test file.

Best, Zejin

**Comment by oyamad** [comment]
@shizejin Very good!

Some thoughts/comments:

* [x] Maybe better to code a generator version too.
* [x] I don't think `verbose` mode is necessary.
* [x] An empty list should be returned when the game has no pure Nash.
* [x] Check the code with pep8.
* [x] Add to the test a game with more than two players.

Can we talk at the office hours today?

**Comment by shizejin** [comment]
Thank you very much for your suggestions! Today I have no econometrics class so see you at 2pm!

**Comment by oyamad** [comment]
```py
NEs = [(0,)*N]
for k in range(2, N-2+1):
    for ind in itertools.combinations(range(N), k):
        a = np.ones(N, dtype=int)
        a[[ind]] = 0
        NEs.append(tuple(a))
NEs.append((1,)*N)
```

**Comment by shizejin** [comment]
Dear professor Oyama,

I've made a pull request [here](https://github.com/QuantEcon/QuantEcon.py/pull/276).

After leaving your office I tried some squashed commitment and force pushing, and sadly messes up my forked repository in final... So I deleted the old repository and tried again.

**Comment by oyamad** [comment]
@shizejin Congratulations, your first PR has been merged.
